name: taskweaver
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
    - torch
    - transformers
    - peft
    - datasets
    - tqdm
    - accelerate
    - huggingface_hub
    - einops
    - matplotlib
    - pandas
    - numpy
    - seaborn
    - python-dotenv
    - jsonargparse
