name: taskweaver
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
    - torch
    - transformers
    - datasets
    - tqdm
    - accelerate
    - huggingface_hub
    - ipykernel
